/****** Script for SelectTopNRows command from SSMS  ******/
SELECT TOP (1000) [EMP_ID]
      ,[EMP_NAME]
      ,[SALARY]
      ,[AGE]
      ,[DEPARTMENT]
      ,[COUNTRY]
      ,[GENDER]
  FROM [MARIA].[dbo].[EMPLOYEES]

  SELECT EMP_NAME NAME, SALARY SAL FROM EMPLOYEES

  SELECT * FROM EMPLOYEES
  WHERE COUNTRY BETWEEN 'UK' AND 'USA'

  SELECT * FROM EMPLOYEES
  WHERE EMP_NAME LIKE 'A%'

  SELECT * FROM EMPLOYEES
  WHERE SALARY >= 500000

CREATE TABLE CUSTOMERSS(ID INT PRIMARY KEY IDENTITY(1,1), NAME VARCHAR(50),AGE INT)

DROP TABLE CUSTOMERSS

DROP TABLE ORDERS



INSERT INTO CUSTOMERSS
VALUES
('JOHN',23),
('ADA', 26),
('PAUL', 30),
('PETER',31),
('JUDAS',34),
('EDU', 46)

SELECT * FROM CUSTOMERSS

CREATE TABLE ORDERS(ORDER_ID INT PRIMARY KEY IDENTITY(10,10),
QUANTITY INT, ITEM VARCHAR(50))

ALTER TABLE ORDERS
ADD ID INT FOREIGN KEY REFERENCES CUSTOMERSS(ID)

SELECT * FROM ORDERS

INSERT INTO ORDERS
VALUES
(12,'PEN',1),
(14,'PENCIL',2)

ALTER TABLE ORDERS
ADD FOREIGN KEY(ID2) REFERENCES CUSTOMERSS(ID)

CREATE TABLE CUSTOMERSS(ID INT PRIMARY KEY IDENTITY(1,1),
NAME VARCHAR(50),AGE INT)

SELECT * FROM CUSTOMERSS
SELECT * FROM ORDERS

CREATE TABLE ORDERS(ORDER_ID INT PRIMARY KEY IDENTITY(10,10),
QUANTITY INT, ITEM VARCHAR(50), ID INT FOREIGN KEY REFERENCES CUSTOMERSS(ID))

INSERT INTO ORDERS
VALUES
(27, 'KEYBOARD', 3)

(19,'PLASMA TV',6)

ALTER TABLE ORDERS
ADD ID2 INT FOREIGN KEY REFERENCES CUSTOMERSS(ID)
