/****** Script for SelectTopNRows command from SSMS  ******/
SELECT TOP (1000) [STATE]
      ,[REGION]
      ,[PRIVATE_MALE_SAT]
      ,[PRIVATE_MALE_PASSED]
      ,[PRIVATE_FEMALE_SAT]
      ,[PRIVATE_FEMALE_PASSED]
      ,[TOTAL_PRIVATE_SAT]
      ,[PRIVATE_TOTAL_PASSED]
      ,[PERCENTAGE PRIVATE]
      ,[PUBLIC_MALE]
      ,[PUBLIC_FEMALE]
      ,[TOTAL_PUBLIC_SAT]
      ,[MALE_PUBLIC_PASSED]
      ,[FEMALE_PUBLIC_PASSED]
      ,[PUBLIC_TOTAL_PASSED]
      ,[PERCENTAGE PUBLIC]
  FROM [ANALYSIS].[dbo].[WAEC]

  /*TOTAL ENROLLMENT*/
  SELECT (SUM(TOTAL_PRIVATE_SAT) + SUM(TOTAL_PUBLIC_SAT)) AS [TOTAL ENROLLMENT] FROM WAEC

  
  /*TOTAL PASSED*/
  SELECT (SUM(PRIVATE_TOTAL_PASSED) + SUM(PUBLIC_TOTAL_PASSED)) AS [TOTAL PASSED] FROM WAEC

  /*PERCENTAGE PASSED PRIVATE*/
  SELECT (sum(PRIVATE_TOTAL_PASSED) * 100.0 /sum(TOTAL_PRIVATE_SAT)) AS [ PERCENTAGE PRIVATE] 
  FROM WAEC

  
  /*PERCENTAGE PASSED PUBLIC*/
  SELECT (sum(PUBLIC_TOTAL_PASSED) * 100.0 /sum(TOTAL_PUBLIC_SAT)) AS [ PERCENTAGE PUBLIC] 
  FROM WAEC

  /* TOTAL PUBLIC SAT */
  SELECT SUM(TOTAL_PUBLIC_SAT) AS [TOTAL PUBLIC SAT] FROM WAEC

    /* TOTAL PRIVATE SAT */
  SELECT SUM(TOTAL_PRIVATE_SAT) AS [TOTAL PRIVATE SAT] FROM WAEC

    /* TOTAL PUBLIC PASSED */
  SELECT SUM(PUBLIC_TOTAL_PASSED) AS [TOTAL PUBLIC PASSED] FROM WAEC

     /* TOTAL PRIVATE PASSED */
  SELECT SUM(PRIVATE_TOTAL_PASSED) AS [TOTAL PRIVATE PASSED] FROM WAEC

  /* TOTAL MALE ENROLLED */
  SELECT SUM(PRIVATE_MALE_SAT) + SUM(PUBLIC_MALE) AS [ TOTAL MALE ENROLLED] FROM WAEC

    /* TOTAL FEMALE ENROLLED */
  SELECT SUM(PRIVATE_FEMALE_SAT) + SUM(PUBLIC_FEMALE) AS [ TOTAL FEMALE ENROLLED] FROM WAEC

  /* TOTAL MALE PASSED */
  SELECT SUM(PRIVATE_MALE_PASSED) + SUM(MALE_PUBLIC_PASSED) AS [TOTAL MALE PASSED] FROM WAEC

    /* TOTAL FEMALE PASSED */
  SELECT SUM(PRIVATE_FEMALE_PASSED) + SUM(FEMALE_PUBLIC_PASSED) AS [TOTAL FEMALE PASSED] FROM WAEC

  /* PERCENTAGE MALE PASSED*/
  SELECT ((SUM(PRIVATE_MALE_PASSED) + SUM(MALE_PUBLIC_PASSED)) * 100.0) / (SUM(PRIVATE_TOTAL_PASSED) + SUM(PUBLIC_TOTAL_PASSED))
  AS [ PERCENTAGE MALE PASSED] 
  FROM WAEC

  /* PERCENTAGE FEMALE PASSED */
  SELECT ((SUM(PRIVATE_FEMALE_PASSED) + SUM(FEMALE_PUBLIC_PASSED)) * 100.0) / (SUM(PRIVATE_TOTAL_PASSED) + SUM(PUBLIC_TOTAL_PASSED))
  AS [PERCENTAGE FEMALE PASSED]
  FROM WAEC

  /* REGION WITH THE HIGHEST SAT IN PUBLIC SCHOOLS */
  SELECT REGION, SUM(TOTAL_PUBLIC_SAT) [TOP REGIONS WITH TOTAL SAT IN PUBLIC] FROM WAEC
  GROUP BY REGION
  ORDER BY [TOP REGIONS WITH TOTAL SAT IN PUBLIC] DESC

  
  /* REGION WITH THE HIGHEST SAT IN PRIVATE SCHOOLS */
  SELECT REGION, SUM(TOTAL_PRIVATE_SAT) [TOP REGIONS WITH TOTAL SAT IN PRIVATE] FROM WAEC
  GROUP BY REGION
  ORDER BY [TOP REGIONS WITH TOTAL SAT IN PRIVATE] DESC

   /* REGION WITH THE HIGHEST PASSED IN PUBLIC SCHOOLS */
  SELECT REGION, SUM(PUBLIC_TOTAL_PASSED) [TOP REGIONS WITH TOTAL PASSED IN PUBLIC] FROM WAEC
  GROUP BY REGION
  ORDER BY [TOP REGIONS WITH TOTAL PASSED IN PUBLIC] DESC

   /* TOP 10 REGION WITH THE HIGHEST PASSED IN PRIVATE SCHOOLS */
  SELECT REGION, SUM(PRIVATE_TOTAL_PASSED) [TOP REGIONS WITH TOTAL PASSED IN PRIVATE] FROM WAEC
  GROUP BY REGION
  ORDER BY [TOP REGIONS WITH TOTAL PASSED IN PRIVATE] DESC

  /* REGION WITH THE LEAST SAT IN PRIVATE SCHOOLS */
  SELECT REGION, SUM(TOTAL_PRIVATE_SAT) [REGIONS WITH LEAST TOTAL SAT IN PRIVATE] FROM WAEC
  GROUP BY REGION
  ORDER BY [REGIONS WITH LEAST TOTAL SAT IN PRIVATE]

  /* REGION WITH THE LEAST SAT IN PRIVATE SCHOOLS */
  SELECT REGION, SUM(TOTAL_PRIVATE_SAT) [REGIONS WITH LEAST TOTAL SAT IN PRIVATE] FROM WAEC
  GROUP BY REGION
  ORDER BY [REGIONS WITH LEAST TOTAL SAT IN PRIVATE] 

   /* REGION WITH THE LEAST PASSED IN PUBLIC SCHOOLS */
  SELECT REGION, SUM(PUBLIC_TOTAL_PASSED) [ REGIONS WITH LEAST TOTAL PASSED IN PUBLIC] FROM WAEC
  GROUP BY REGION
  ORDER BY [ REGIONS WITH LEAST TOTAL PASSED IN PUBLIC]

   /* REGION WITH THE LEAST PASSED IN PRIVATE SCHOOLS */
  SELECT REGION, SUM(PRIVATE_TOTAL_PASSED) [REGIONS WITH LEAST TOTAL PASSED IN PRIVATE] FROM WAEC
  GROUP BY REGION
  ORDER BY [REGIONS WITH LEAST TOTAL PASSED IN PRIVATE]

  /* STATE WITH THE HIGHEST SAT IN PUBLIC */
  SELECT STATE, SUM(TOTAL_PUBLIC_SAT) [STATE WITH HIGHEST NUMBER OF SAT IN PUBLIC] FROM WAEC
  GROUP BY STATE
  ORDER BY [STATE WITH HIGHEST NUMBER OF SAT IN PUBLIC] DESC

   /* STATE WITH THE HIGHEST PASSED IN PUBLIC SCHOOLS */
  SELECT STATE, SUM(PUBLIC_TOTAL_PASSED) [ STATE WITH HIGHEST TOTAL PASSED IN PUBLIC] FROM WAEC
  GROUP BY STATE
  ORDER BY [ STATE WITH HIGHEST TOTAL PASSED IN PUBLIC] DESC

   /* STATE WITH THE HIGHEST SAT IN PRIVATE SCHOOLS */
  SELECT STATE, SUM(TOTAL_PRIVATE_SAT) [STATE WITH HIGHEST TOTAL SAT IN PRIVATE] FROM WAEC
  GROUP BY STATE
  ORDER BY [STATE WITH HIGHEST TOTAL SAT IN PRIVATE] DESC

   /* STATE WITH THE HIGHEST PASSED IN PRIVATE*/
   SELECT STATE, SUM(PRIVATE_TOTAL_PASSED) [STATE WITH HIGHEST NUMBER OF PASSED IN PRIVATE] FROM WAEC
  GROUP BY STATE
  ORDER BY [STATE WITH HIGHEST NUMBER OF PASSED IN PRIVATE] DESC

  



