SELECT * FROM HR

/* ROW_NUMBER() ON WINDOW FUNCTION, IT ASSIGNS ROWS TO THE VALUES SPECIFIED*/
SELECT H.EMPID, H.EMPLOYEE_NAME,H.SEX,H.SALARY,H.DEPARTMENT,
ROW_NUMBER() OVER(PARTITION BY H.DEPARTMENT ORDER BY H.EMPID) AS ROW_NUM
FROM HR H

/* TO VIEW THE FIRST 2 EMPLOYEES TO JOIN A DEPARTMENT */
SELECT * FROM(
	SELECT H.EMPID, H.EMPLOYEE_NAME,H.SEX,H.SALARY,H.DEPARTMENT,
	ROW_NUMBER() OVER(PARTITION BY H.DEPARTMENT ORDER BY H.EMPID) AS ROW_NUM
	FROM HR H) R
WHERE R.ROW_NUM < 3

/* HOW TO WORK ON RANK IN SQL,
(Assigns a unique rank to each row, with gaps in rank values for tied rows)
TO SELECT THE EMPLOYEES EARNING THE HIGHEST SALARY TO THE LOWEST*/
SELECT H.EMPLOYEE_NAME,H.SEX,H.SALARY,H.DEPARTMENT,
RANK() OVER(PARTITION BY H.DEPARTMENT ORDER BY H.SALARY DESC) AS RANK_NUM
FROM HR H

/* HOW TO WORK ON DENSE_RANK IN SQL
( Assigns ranks to rows in sequential order, without gaps in ranking values.)*/
SELECT H.EMPLOYEE_NAME,H.SEX,H.SALARY,H.DEPARTMENT,
DENSE_RANK() OVER(PARTITION BY H.DEPARTMENT ORDER BY H.SALARY DESC) AS RANK_NUM
FROM HR H

/* (Gets the first value in a window partition.)
TO GET THE FIRST SALARY FROM EACH OF THE DEPARTMENT */
SELECT H.EMPLOYEE_NAME,H.SEX,H.SALARY,H.DEPARTMENT,
FIRST_VALUE(SALARY) OVER(PARTITION BY H.DEPARTMENT ORDER BY H.SALARY DESC) AS RANK_NUM
FROM HR H


/* CHECKING FOR THE MAX SALARY FOR EACH DEPT */
SELECT H.EMPLOYEE_NAME, H.DEPARTMENT, H.SALARY,
MAX(SALARY) OVER(PARTITION BY H.DEPARTMENT ) AS [MAX SALARY]
FROM HR H

/* CHECKING FOR THE SUM OF SALARY OF EACH OF THE DEPARTMENT */
SELECT H.EMPLOYEE_NAME, H.DEPARTMENT, H.SALARY,
SUM(SALARY) OVER(PARTITION BY H.DEPARTMENT) AS [SUM SALARY]
FROM HR H

/* FETCH THE TOP 3 EMPLOYEES IN EACH DEPT EARNING THE MAX SALARY (RANK) */
SELECT * FROM(
	SELECT H.EMPLOYEE_NAME,H.SEX,H.SALARY,H.DEPARTMENT,
	RANK() OVER(PARTITION BY H.DEPARTMENT ORDER BY H.SALARY DESC) AS RANK_NUM
	FROM HR H) R
WHERE R.RANK_NUM <4

/* FETCH THE TOP 3 EMPLOYEES IN EACH DEPT EARNING THE MAX SALARY ( DENSE_RANK) */
SELECT * FROM(
	SELECT H.EMPLOYEE_NAME,H.SEX,H.SALARY,H.DEPARTMENT,
	DENSE_RANK() OVER(PARTITION BY H.DEPARTMENT ORDER BY H.SALARY DESC) AS RANK_NUM
	FROM HR H) R
WHERE R.RANK_NUM <4

SELECT 
  empid,
  department,
  salary,
  SUM(salary) OVER (PARTITION BY department ORDER BY salary) AS avg_department_salary
FROM 
  HR

  SELECT 
  empid,
  department,
  salary,
  MAX(salary) OVER (PARTITION BY department ORDER BY salary) AS avg_department_salary
FROM 
  HR

  SELECT YEAR(ORDERDATE) [YEAR], REP, REGION, TOTAL,
       PERCENT_RANK() OVER (ORDER BY TOTAL ) AS percent_rank
FROM SALES
WHERE YEAR(ORDERDATE) = 2015



SELECT 
  orderdate,
  rep,
  region,
  item,
  total,
  PERCENT_RANK() OVER (ORDER BY total DESC) AS percent_rank
FROM 
  SALES

  
