SELECT * FROM HR

--WITH CLAUSE
WITH AVERAGE_SALARY (AVG_SAL) AS
	(SELECT AVG(SALARY) FROM HR)
SELECT EMPID,EMPLOYEE_NAME,SALARY,  AVG_SAL
FROM HR, AVERAGE_SALARY

--FIND THE EMPLOYEES WHO'S SALARY WERE BETTER THAN THE AVERAAGE SALARY ACROSS ALL EMPLOYEES

--1-- FIND THE TOTAL SALARY PER EMPLOYEE-- TOTAL_SAL
SELECT EMPLOYEE_NAME, SUM(SALARY) SUM_OF_SALARY FROM HR
GROUP BY Employee_Name

--2-- FIND THE AVERAGE OF SALARY ACROSS ALL EMPLOYEES
SELECT AVG(SUM_OF_SALARY) AS AVG_EMP_SALARY
	FROM (SELECT EMPLOYEE_NAME, SUM(SALARY) SUM_OF_SALARY FROM HR
GROUP BY Employee_Name) H

--3-- FIND THE EMPLOYEES WHERE THEIR TOTAL SALARY > AVG SALARY
SELECT *
   FROM(SELECT EMPLOYEE_NAME, SUM(SALARY) SUM_OF_SALARY FROM HR
      GROUP BY Employee_Name) AS TOTAL_SALARY
JOIN (SELECT AVG(SUM_OF_SALARY) AS AVG_EMP_SALARY
	FROM (SELECT EMPLOYEE_NAME, SUM(SALARY) SUM_OF_SALARY FROM HR
      GROUP BY Employee_Name) H) AS AVG_SALARY
ON TOTAL_SALARY.SUM_OF_SALARY > AVG_SALARY.AVG_EMP_SALARY


-- USING A WITH CLAUSE FOR THE ABOVE QUERY
WITH TOTAL_SALARY (EMPLOYEE_NAME, SUM_OF_SALARY) AS 
		(SELECT EMPLOYEE_NAME, SUM(SALARY) SUM_OF_SALARY FROM HR
		GROUP BY Employee_Name),
	AVG_SALARY (AVG_EMP_SALARY) AS
	    (SELECT AVG(SUM_OF_SALARY) AS AVG_EMP_SALARY
		FROM TOTAL_SALARY)
SELECT *
FROM TOTAL_SALARY TS
JOIN AVG_SALARY ASG
ON TS.SUM_OF_SALARY > ASG.AVG_EMP_SALARY
